/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "XXXXXX",
    "aws_cognito_identity_pool_id": "ap-northeast-1:xxxx",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_XXXXX",
    "aws_user_pools_web_client_id": "XXXXXX",
    "oauth": {},
    "aws_user_files_s3_bucket": "XXXXXX",
    "aws_user_files_s3_bucket_region": "XXXXXX"
};


export default awsmobile;
